import Serializer from "./serializer";
declare const operation: any;
export { operation };
export declare let void_ext: Serializer<{}>;
export declare const transfer_operation_fee_parameters: Serializer<{}>;
export declare const limit_order_create_operation_fee_parameters: Serializer<{}>;
export declare const limit_order_cancel_operation_fee_parameters: Serializer<{}>;
export declare const call_order_update_operation_fee_parameters: Serializer<{}>;
export declare const fill_order_operation_fee_parameters: Serializer<{}>;
export declare const account_create_operation_fee_parameters: Serializer<{}>;
export declare const account_update_operation_fee_parameters: Serializer<{}>;
export declare const account_whitelist_operation_fee_parameters: Serializer<{}>;
export declare const account_upgrade_operation_fee_parameters: Serializer<{}>;
export declare const account_transfer_operation_fee_parameters: Serializer<{}>;
export declare const asset_create_operation_fee_parameters: Serializer<{}>;
export declare const asset_update_operation_fee_parameters: Serializer<{}>;
export declare const asset_update_bitasset_operation_fee_parameters: Serializer<{}>;
export declare const asset_update_feed_producers_operation_fee_parameters: Serializer<{}>;
export declare const asset_issue_operation_fee_parameters: Serializer<{}>;
export declare const initiate_crowdfund_operation_fee_parameters: Serializer<{}>;
export declare const participate_crowdfund_operation_fee_parameters: Serializer<{}>;
export declare const withdraw_crowdfund_operation_fee_parameters: Serializer<{}>;
export declare const asset_reserve_operation_fee_parameters: Serializer<{}>;
export declare const asset_fund_fee_pool_operation_fee_parameters: Serializer<{}>;
export declare const asset_settle_operation_fee_parameters: Serializer<{}>;
export declare const asset_global_settle_operation_fee_parameters: Serializer<{}>;
export declare const asset_publish_feed_operation_fee_parameters: Serializer<{}>;
export declare const witness_create_operation_fee_parameters: Serializer<{}>;
export declare const witness_update_operation_fee_parameters: Serializer<{}>;
export declare const proposal_create_operation_fee_parameters: Serializer<{}>;
export declare const proposal_update_operation_fee_parameters: Serializer<{}>;
export declare const proposal_delete_operation_fee_parameters: Serializer<{}>;
export declare const withdraw_permission_create_operation_fee_parameters: Serializer<{}>;
export declare const withdraw_permission_update_operation_fee_parameters: Serializer<{}>;
export declare const withdraw_permission_claim_operation_fee_parameters: Serializer<{}>;
export declare const withdraw_permission_delete_operation_fee_parameters: Serializer<{}>;
export declare const committee_member_create_operation_fee_parameters: Serializer<{}>;
export declare const committee_member_update_operation_fee_parameters: Serializer<{}>;
export declare const committee_member_update_global_parameters_operation_fee_parameters: Serializer<{}>;
export declare const vesting_balance_create_operation_fee_parameters: Serializer<{}>;
export declare const vesting_balance_withdraw_operation_fee_parameters: Serializer<{}>;
export declare const worker_create_operation_fee_parameters: Serializer<{}>;
export declare const custom_operation_fee_parameters: Serializer<{}>;
export declare const assert_operation_fee_parameters: Serializer<{}>;
export declare const balance_claim_operation_fee_parameters: Serializer<{}>;
export declare const override_transfer_operation_fee_parameters: Serializer<{}>;
export declare const transfer_to_blind_operation_fee_parameters: Serializer<{}>;
export declare const blind_transfer_operation_fee_parameters: Serializer<{}>;
export declare const transfer_from_blind_operation_fee_parameters: Serializer<{}>;
export declare const asset_settle_cancel_operation_fee_parameters: Serializer<{}>;
export declare const asset_claim_fees_operation_fee_parameters: Serializer<{}>;
export declare const fee_schedule: Serializer<{}>;
export declare const void_result: Serializer<{}>;
export declare const asset: Serializer<{}>;
export declare const processed_transaction: Serializer<{}>;
export declare const signed_block: Serializer<{}>;
export declare const block_header: Serializer<{}>;
export declare const signed_block_header: Serializer<{}>;
export declare const memo_data: Serializer<{}>;
export declare const transfer: Serializer<{}>;
export declare const limit_order_create: Serializer<{}>;
export declare const limit_order_cancel: Serializer<{}>;
export declare const call_order_update: Serializer<{}>;
export declare const fill_order: Serializer<{}>;
export declare const authority: Serializer<{}>;
export declare const account_options: Serializer<{}>;
export declare const account_create: Serializer<{}>;
export declare const account_update: Serializer<{}>;
export declare const account_whitelist: Serializer<{}>;
export declare const account_upgrade: Serializer<{}>;
export declare const account_transfer: Serializer<{}>;
export declare const price: Serializer<{}>;
export declare const asset_options: Serializer<{}>;
export declare const bitasset_options: Serializer<{}>;
export declare const asset_create: Serializer<{}>;
export declare const asset_update: Serializer<{}>;
export declare const asset_update_bitasset: Serializer<{}>;
export declare const asset_update_feed_producers: Serializer<{}>;
export declare const asset_issue: Serializer<{}>;
export declare const asset_reserve: Serializer<{}>;
export declare const asset_fund_fee_pool: Serializer<{}>;
export declare const asset_settle: Serializer<{}>;
export declare const asset_global_settle: Serializer<{}>;
export declare const participate_crowdfund: Serializer<{}>;
export declare const withdraw_crowdfund: Serializer<{}>;
export declare const initiate_crowdfund: Serializer<{}>;
export declare const price_feed: Serializer<{}>;
export declare const asset_publish_feed: Serializer<{}>;
export declare const witness_create: Serializer<{}>;
export declare const witness_update: Serializer<{}>;
export declare const op_wrapper: Serializer<{}>;
export declare const proposal_create: Serializer<{}>;
export declare const proposal_update: Serializer<{}>;
export declare const proposal_delete: Serializer<{}>;
export declare const withdraw_permission_create: Serializer<{}>;
export declare const withdraw_permission_update: Serializer<{}>;
export declare const withdraw_permission_claim: Serializer<{}>;
export declare const withdraw_permission_delete: Serializer<{}>;
export declare const committee_member_create: Serializer<{}>;
export declare const committee_member_update: Serializer<{}>;
export declare const chain_parameters: Serializer<{}>;
export declare const committee_member_update_global_parameters: Serializer<{}>;
export declare const linear_vesting_policy_initializer: Serializer<{}>;
export declare const cdd_vesting_policy_initializer: Serializer<{}>;
export declare const vesting_balance_create: Serializer<{}>;
export declare const vesting_balance_withdraw: Serializer<{}>;
export declare const refund_worker_initializer: Serializer<{}>;
export declare const vesting_balance_worker_initializer: Serializer<{}>;
export declare const burn_worker_initializer: Serializer<{}>;
export declare const worker_create: Serializer<{}>;
export declare const custom: Serializer<{}>;
export declare const account_name_eq_lit_predicate: Serializer<{}>;
export declare const asset_symbol_eq_lit_predicate: Serializer<{}>;
export declare const block_id_predicate: Serializer<{}>;
export declare const assert: Serializer<{}>;
export declare const balance_claim: Serializer<{}>;
export declare const override_transfer: Serializer<{}>;
export declare const stealth_confirmation: Serializer<{}>;
export declare const blind_output: Serializer<{}>;
export declare const transfer_to_blind: Serializer<{}>;
export declare const blind_input: Serializer<{}>;
export declare const blind_transfer: Serializer<{}>;
export declare const transfer_from_blind: Serializer<{}>;
export declare const asset_settle_cancel: Serializer<{}>;
export declare const asset_claim_fees: Serializer<{}>;
export declare const transaction: Serializer<{}>;
export declare const signed_transaction: Serializer<{}>;
export declare const stealth_memo_data: Serializer<{}>;
export declare const fund_query: Serializer<{}>;
export declare type RequestWithExpire = {
    expiration: number;
};
export declare type BackendRequestMethod = "query" | "create";
export declare type BackendRequest<BackendRequestMethod> = {
    signature: string;
    method: BackendRequestMethod;
};
export declare type SetAddress = {
    loginName: string;
    receiverName: string;
    email: string;
    qqNo: string;
    wechatNo: string;
    proviceId: number;
    homeAddress: string;
};
export declare type SetAddressWithExpire = SetAddress & RequestWithExpire;
export declare type SetAddressRequest = SetAddressWithExpire & BackendRequest<"create">;
export declare type GetAddress = {
    loginName: string;
};
export declare type GetAddressWithExpire = GetAddress & RequestWithExpire;
export declare type GetAddressRequest = GetAddressWithExpire & BackendRequest<"query">;
export declare type SetRefer = {
    action: string;
    referrer: string;
    account: string;
};
export declare type SetReferRequest = GetAddressWithExpire & RequestWithExpire;
export declare const set_refer: Serializer<GetAddressWithExpire>;
export declare const query_address: Serializer<GetAddressWithExpire>;
export declare const set_address: Serializer<SetAddressWithExpire>;
